name: Dockerize and Push

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    name: Dockerize
    runs-on: [ubuntu-latest]
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Docker Login
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push
        if: github.event_name == 'push'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
          SERVICE: rpi-pir-sensor
        run: |
          docker build -t $DOCKERHUB_USERNAME/$SERVICE:$IMAGE_TAG -t $DOCKERHUB_USERNAME/$SERVICE:latest -f DockerfilePi .
          docker push $DOCKERHUB_USERNAME/$SERVICE:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$SERVICE:latest